### ISSUE TITLE
[CreateChannels] Suggestion: Syncing Permissions with Category

### ISSUE THREAD

**Issue by emshov74** [Obi-Wan3/OB13-Cogs#11]
**Feature Description**
Hi, I would like to see implemented where the permissions sync with the category, because this doesn't happen for me at the moment.

**Alternatives Considered**
The roomtools cog from https://github.com/mikeshardmind/SinbadCogs has a tmpc command which functions "the right way" and syncs permissions from the category. I can't use that cog because another command in it (autoroomset) conflicts with another cog that uses the same command name.

**Additional Context**
These are the perms which I get when I have a VC made.
![image](https://user-images.githubusercontent.com/36211362/116934566-6caec700-ac65-11eb-84d8-b8a7b9b34822.png)

**Comment by Obi-Wan3** [comment]
Thanks for bringing this to my attention, it should have been implemented in f69ed1a552e06855032432da01e6b82b48af7738 but let me know if something does not work as expected.
