### ISSUE TITLE
[Counting] Suggestion: Leaderboard

### ISSUE THREAD

**Issue by Srcsm** [Obi-Wan3/OB13-Cogs#12]
**Feature Description**
A leaderboard for only the top 3 users, or optionally more if preferred.

Something similar to,

> **Top 3 Counters**
>
>1. User1 - 548 times!
>2. User2 - 329 times!
>3. User3 - 261 times!
>
>Most Recent Count made by **User**

_**Have this is an optional feature that can be enabled or disabled.**_
ㅤ
ㅤ
**Alternatives Considered**
Alternatively a command that can call the user with the most 'counts' `[p]counting leader`

ㅤ
**Additional Context**
I used [Embed-Creator](https://robyul.chat/embed-creator) to make a quick idea for visual,
![countleader](https://user-images.githubusercontent.com/11580870/117590202-7021d280-b0eb-11eb-9e80-f4e6e950504f.png)

For alternative, single leader,
![countleader2](https://user-images.githubusercontent.com/11580870/117590355-49b06700-b0ec-11eb-826c-734859f58dd1.png)

**Comment by Obi-Wan3** [comment]
Hey @Srcsm, thanks for suggesting this for `Counting`. I agree that it would be a good addition, and will work on it when I have time. I'll likely implement a leaderboard for up to the top 10 users.

**Comment by Obi-Wan3** [comment]
@Srcsm I just implemented this feature, `[p]topcounters` for the Top 10 Leaderboard.

**Comment by Srcsm** [comment]
Wow, thank you! :)
