### ISSUE TITLE
[BrainShop] Suggestion: Channel Block/Allowlist

### ISSUE THREAD

**Issue by xSignificant** [Obi-Wan3/OB13-Cogs#13]
**Feature Description**
Only allowing the bot to respond in whitelisted channels. 
Not allowing the bot to respond in blacklisted channels.

**Comment by Obi-Wan3** [comment]
Hey, thanks for making this feature request, I'll work on adding a block/allowlist feature when I have time.

**Comment by Obi-Wan3** [comment]
@xSignificant Just implemented! `[p]brainshopset allowlist` and `[p]brainshopset blocklist`, as well as `[p]brainshopset view` for the current server settings.
