### ISSUE TITLE
[LFG] Suggestion: Toggleable Response on `[p]lfg` w/o Inputs

### ISSUE THREAD

**Issue by sp00nd** [Obi-Wan3/OB13-Cogs#14]
**Feature Description**
Toggleable: If member runs `[p]lfg` command without any parameters, it will still post the VC invite, then below it will show the current "help" on adding values.

**Alternatives Considered**
A friend of mine wanted to use retrigger to do this, I think it would be better to simply add it to the cog itself.

**Additional Context**
Many just want to run `[p]lfg` without params and get the invite out, this would assist in them avoiding reading. Nobody likes reading stuff in 2021 🙂

**Comment by Obi-Wan3** [comment]
Thanks for the feature request, I'll be working on this when I have time.

**Comment by Obi-Wan3** [comment]
Just implemented this with `[p]lfgset noinputs` for a secondary template also functioning as the toggle.
