### ISSUE TITLE
[Counting] Suggestion: Highscore & Reactions

### ISSUE THREAD

**Issue by XargsUK** [Obi-Wan3/OB13-Cogs#17]
**Feature Description**

- High score command so the guild can see the highest number they've achieved (if the auto-reset feature is enabled).
  - `[p]counting highscore` - Returns the high score of the guild. Bot returns something like "{servername}'s counting highscore is 520!"

- Toggle for reacting with ✓ and ✗ on messages to confirm if the counts were successful.
  -  `[p]counting reactconfirm <true_or_false>`

**Additional Context**
With the introduction of autoreset, confirmations on messages would help users to know that their message has been counted. For example, if the number is up to 50 and the bot owner is doing maintenance, users could be messaging the next numbers in the channel during this. Once the service of the bot is resumed, a user may enter a number which may be correct in the context of the channel, but incorrect as the bot was not able to process the numbers during the downtime. Reactions to messages ensures users know that their message has been counted.

**Comment by Obi-Wan3** [comment]
Hey @XargsUK, thanks for the suggestions! I'll look into implementing these when I am available.

Another idea I had (putting it here so I don't forget) following our conversation about the "auto-reset" feature/message was adding the `{correct}` variable to indicate what the correct number should have been.

**Comment by XargsUK** [comment]
> Another idea I had (putting it here so I don't forget) following our conversation about the "auto-reset" feature/message was adding the `{correct}` variable to indicate what the correct number should have been.

I was going to suggest this as well! Completely agree with the `{correct}` variable. Thanks for your amazing work on this @Obi-Wan3

**Comment by Obi-Wan3** [comment]
@XargsUK These features have been implemented! Thanks again for the suggestions.
