### ISSUE TITLE
[counting] Suggestion: React confirmation on numbers 

### ISSUE THREAD

**Issue by XargsUK** [Obi-Wan3/OB13-Cogs#18]
**Feature Description**
When a user messages the next number into the channel, a reaction is placed on the message confirming whether or not it was correct (tick or cross).

**Additional Context**
With the introduction of autoreset, confirmations on messages would help users to know that their message has been counted. For example, if the number is up to 50 and the bot owner is doing maintenance, users could be messaging the next numbers in the channel during this. Once the service of the bot is resumed, a user may enter a number which may be correct in the context of the channel, but incorrect as the bot was not able to process the numbers during the downtime.  Reactions to messages ensures users know that their message has been counted.

**Comment by Obi-Wan3** [comment]
I just merged your suggestion here with the previous issue, as I had already started the process for that from our conversation in my support channel and I did not realize you were planning on making 2 separate issues. Thanks again for the suggestions :)
