### ISSUE TITLE
[SimpleCalculator] Suggestion: More Informative Help

### ISSUE THREAD

**Issue by ExpertNugget** [Obi-Wan3/OB13-Cogs#24]
When you run just [p]calc it responds with [p]calc <query>. It would be awesome if it told you what kind of symbols you can put into the query ex:
Multiplication = *
Tangent = tan(<num>)
Ect
Just a quality of life thing really but would be very useful instead of just trial and error to find the right symbols

**Comment by Obi-Wan3** [comment]
@ExpertNugget I appreciate you taking the time to fill out a feature request, however SimpleCalculator is by [Phenom4n4n](https://github.com/phenom4n4n/phen-cogs) and is not in my repo, so this issue should probably go there instead :P

**Comment by ExpertNugget** [comment]
Reminder to self run [p]findcog before making a request now I feel dumb sorry bout that
