### ISSUE TITLE
[Leveler] Suggestion: Prestige Mode

### ISSUE THREAD

**Issue by EternalllZM** [Obi-Wan3/OB13-Cogs#26]
**Feature Description**
Understandably the cog is not out yet so not much is known. However, I would like to suggest something that likely should be done earlier in development. A Prestige Mode is similar to games with this feature where you can reset your "levels" for an overall role increase, and then climb the same ranks again up until a certain max prestige. This would encourage further activity even after a member has "maxed out".

**Alternatives Considered**
N/A

**Additional Context**
I will go with an example of how this would work:

1. You are at rank or level 50, which gives you the highest Leveler role in the server regarding _levels_. 
2. You enter prestige mode, and return to rank 1 in terms of _levels_.
3. However, you have received the "Prestige 1" role, a "Prestige 1" labeling within Leveler, and can climb back up to rank 50 to receive prestige 2. So on and so forth.
4. _Ideally, this does not reset overall stats, only the "level" roles applied, and the internal "level" via Leveler. Either do not have it reset overall stats, or add a toggle for the prestige mode settings._

**Comment by Obi-Wan3** [comment]
@sp00nd Thanks for the suggestion, this is quite an interesting idea and I will consider incorporating it.
