### ISSUE TITLE
PublicRooms Displays Incorrect Information when Editing Name

### ISSUE THREAD

**Issue by sp00nd** [Obi-Wan3/OB13-Cogs#3]
When first creating a PublicRoom system, the following will display for the name:
**For the channel_name_template, enter a string, with {num} contained if you want it to be replaced with the number of active VCs.**

However, when _editing_ the name of the system, you will be met with the following:
**Enter a string, with {creator} contained if you want it to be replaced with the VC creator's display name.**

{creator} does not work with PublicRooms. However, it does work with PrivateRooms. The best solution in this case would be to make both options work on both systems. As both can identify the invoker of the channel creation.

**Comment by Obi-Wan3** [comment]
Thanks for reporting this! I think I just forgot to replace a docstring, as PrivateRooms was created first and quite a bit of code was reused between them. For making the `{creator}` option work on both of them, I don't think I will be adding that as I don't think the point of PublicRooms reflects having a room creator's name in the channel. However, I will definitely be fixing that docstring to have the correct instructions (that should be pushed in a few minutes, at which point I will also close this issue).
