### ISSUE TITLE
[StatusRole] Suggestion: Any Emoji From Current Guild

### ISSUE THREAD

**Issue by Ibotmealot** [Obi-Wan3/OB13-Cogs#6]
**Feature Description**
The ability for the required emoji to be from the current guild. This would be nice to give users a role who are using the emotes that your server has. 

**Alternatives Considered**
None. 

**Additional Context**
Nope.

**Comment by Obi-Wan3** [comment]
Hey, thanks for this feature request! I think that this would be a good addition, and will be working on this when I have time.

**Comment by Obi-Wan3** [comment]
@Ibotmealot Just implemented this!
